/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cliente;

import cliente.Socket_Cliente;

/**
 *
 * @author a1655086
 */
public class FrameCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrameCliente
     */
    public FrameCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textoRecebimento = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        campoTextoPortaServidor = new javax.swing.JTextField();
        LigarServidor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoTextoIpCliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoEntrada = new javax.swing.JTextArea();
        campoTextoPortaCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buttonConectar = new javax.swing.JButton();
        buttonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoRecebimento.setColumns(20);
        textoRecebimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textoRecebimento.setRows(5);
        jScrollPane1.setViewportView(textoRecebimento);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("PORT");

        campoTextoPortaServidor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoTextoPortaServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoPortaServidorActionPerformed(evt);
            }
        });

        LigarServidor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LigarServidor.setText("Ligar");
        LigarServidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LigarServidorMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("IP");

        campoTextoIpCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoTextoIpCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoIpClienteActionPerformed(evt);
            }
        });

        textoEntrada.setColumns(20);
        textoEntrada.setRows(5);
        jScrollPane2.setViewportView(textoEntrada);

        campoTextoPortaCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoTextoPortaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoPortaClienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("PORT");

        buttonConectar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buttonConectar.setText("Conectar");
        buttonConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonConectarMouseClicked(evt);
            }
        });

        buttonEnviar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buttonEnviar.setText("Enviar");
        buttonEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEnviarMouseClicked(evt);
            }
        });
        buttonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoTextoPortaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LigarServidor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoTextoIpCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTextoPortaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonConectar)
                        .addGap(141, 141, 141)
                        .addComponent(buttonEnviar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoPortaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LigarServidor)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoTextoPortaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConectar)
                    .addComponent(buttonEnviar)
                    .addComponent(campoTextoIpCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void campoTextoPortaServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoPortaServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoPortaServidorActionPerformed
*/
    private void LigarServidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LigarServidorMouseClicked
       
    }//GEN-LAST:event_LigarServidorMouseClicked
/*
    private void campoTextoIpClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoIpClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoIpClienteActionPerformed

    private void campoTextoPortaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoPortaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoPortaClienteActionPerformed
*/
    private void buttonConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonConectarMouseClicked
        Socket_Cliente cliente = new Socket_Cliente(campoTextoIpCliente.getText(), Integer.valueOf(campoTextoPortaCliente.getText()));
        Thread t = new Thread(cliente);
    }//GEN-LAST:event_buttonConectarMouseClicked

    private void buttonEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnviarMouseClicked

    }//GEN-LAST:event_buttonEnviarMouseClicked
/*
    private void buttonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEnviarActionPerformed
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LigarServidor;
    private javax.swing.JButton buttonConectar;
    private javax.swing.JButton buttonEnviar;
    public static javax.swing.JTextField campoTextoIpCliente;
    public static javax.swing.JTextField campoTextoPortaCliente;
    public static javax.swing.JTextField campoTextoPortaServidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textoEntrada;
    private javax.swing.JTextArea textoRecebimento;
    // End of variables declaration//GEN-END:variables
}
